### PR TITLE
Use a Map instead of an object to get unique mappings for boot entries

### PR DESCRIPTION
**Pull request by pdamianik**
At the moment the efimanager command sets boot next to the index of the boot entry in the command output, as the array (with integer keys) gets spread into the object. Also Maps are the intended way to store unique key value pairs in JS (afaik).

### CODE REVIEW

**Comment by tiagoporsch** [comment]
Seems good to me. I don't have much experience in JS so I just kind of do what works. Thank you!

**Comment by pdamianik** [comment]
> Seems good to me. I don't have much experience in JS so I just kind of do what works. Thank you!

No worries, I'm a bit out of practice myself. Also thanks for the extension, I planned to do it myself, but then I found yours and while it didn't work initially, I think it's a better idea to improve the existing thing instead of starting from scratch.

**Comment by pdamianik** [comment]
Btw do you have a planned release date for the next update?

**Comment by tiagoporsch** [comment]
I think your `pkexec` change is very important, so I already repackaged the extension and submitted to the GNOME Extensions website. It should soon be reviewed and accepted.

**Comment by pdamianik** [comment]
Update is here :tada: 
image

**Pull request merged**
